spring:
  application:
    name: hiremate
  profiles:
    active: dev
  security:
    user:
      name: iiita
      password: iiita123
      roles: ADMIN
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    retry:
      enabled: false
    google:
      genai:
        api-key: ${geminiApiKey}
        chat:
          options:
            model: ${geminiModel}



  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

jwt:
  secretKey: ${jwtSecret}

cloudinary:
  cloud_name: ${cloudName}
  api_key: ${apiKey}
  api_secret: ${apiSecret}
  path:
    resume: resume